//REGISTER USER
# POST http://localhost:4000/api/users/register
# Content-Type: application/json

# {
#   "username": "Milu",
#   "password": "Milupassword123",
#   "userType": 0
# }


# //LOGIN USER TO GET TOKEN
# POST http://localhost:4000/api/users/login
# Content-Type: application/json

# {
#   "username": "Sulle",
#   "password": "Sullepassword123"
# }


//CHECK AUTHENTICATON(PROTECTED ROUTE)
# GET http://localhost:4000/api/protected
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1pbHUiLCJ1c2VyVHlwZSI6MCwiaWF0IjoxNzM1NjE5OTM2LCJleHAiOjE3MzU2MjM1MzZ9.1lvs2jUnBatQEEnKt9ZDl5phKMlzAB-zbJnJwHX1smQ


//ADD PRODUCT BY SELLER (NEED FOR POSTMAN BECAUSE OF IMAGE FILE UPLOAD)
# POST http://localhost:4000/api/seller/add-product
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJNaWx1IiwidXNlclR5cGUiOjAsImlhdCI6MTczNTg3OTQzMCwiZXhwIjoxNzM1ODgzMDMwfQ.bnvgN7UD2st9rkrGWKpS6Ve1wMRgo0KZ_7Om2HJYZ_U
# Content-Type: application/json

# {
#     "name": "Mouse",
#     "description": "A high-performance gaming mouse",
#     "price": 1500,
#     "image": "@/mouse.jpeg"
# }


//CHANGE PRICE FOR PRODUCT FOR SELLER
# POST http://localhost:4000/api/seller/set-price
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJNaWx1IiwidXNlclR5cGUiOjAsImlhdCI6MTczNjQwMDk0MSwiZXhwIjoxNzM2NDA0NTQxfQ.UxQSpowvHV7YdIQJPmtNCAlTC6ovo8GEqDG2GAeD--E
# Content-Type: application/json

# {
#   "productId": 6,
#   "newPrice": 1300
# }


//VIEW ALL PRODUCTS FOR CUSTOMER
# GET http://localhost:4000/api/customer/products
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBYmh5dWRheWEiLCJ1c2VyVHlwZSI6MSwiaWF0IjoxNzM1NjM0NDM5LCJleHAiOjE3MzU2MzgwMzl9.WhKO9ZespFUDkKuEXb9WSYrl7dgNfbZiVbITDi-ohbk


//ADD TO CART FOR CUSTOMER
# POST http://localhost:4000/api/customer/cart
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBYmh5dWRheWEiLCJ1c2VyVHlwZSI6MSwiaWF0IjoxNzM1ODgwNjM3LCJleHAiOjE3MzU4ODQyMzd9.d7b_nBzrMZ28vcb2o342gyzNK_wsZOsnOOCG2HvbzK0
# Content-Type: application/json

# {
#     "productId": 1,
#     "quantity": 2
# }


//VIEW CART FOR CUSTOMER
# GET http://localhost:4000/api/customer/cart
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJTdWxsZSIsInVzZXJUeXBlIjoxLCJpYXQiOjE3MzY5MjAwNTgsImV4cCI6MTczNjkyMzY1OH0.nJ6Zrxp0SqIEk3lSJ_U0xgkKcFYz0Ag_x8Xw8R_FZ14

//DELETE FROM CART FOR CUSTOMER
# DELETE  http://localhost:4000/api/customer/cart
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBYmh5dWRheWEiLCJ1c2VyVHlwZSI6MSwiaWF0IjoxNzM1NjI0OTM0LCJleHAiOjE3MzU2Mjg1MzR9.0aCU7uhY7lPaGgQxmQDSnJerR9I4ixNXErq0hj57rX4
# Content-Type: application/json

# {
#     "cartItemId": 3
# }


//BUY FOR CUSTOMER
# POST http://localhost:4000/api/customer/buy
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBYmh5dWRheWEiLCJ1c2VyVHlwZSI6MSwiaWF0IjoxNzM1ODgwNjM3LCJleHAiOjE3MzU4ODQyMzd9.d7b_nBzrMZ28vcb2o342gyzNK_wsZOsnOOCG2HvbzK0
# Content-Type: application/json


//GET ORDER HISTORY FOR CUSTOMER
# GET http://localhost:4000/api/customer/orders
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJBYmh5dWRheWEiLCJ1c2VyVHlwZSI6MSwiaWF0IjoxNzM1ODgwNjM3LCJleHAiOjE3MzU4ODQyMzd9.d7b_nBzrMZ28vcb2o342gyzNK_wsZOsnOOCG2HvbzK0